# Lab 7: Investing time in functions and data structures

Welcome to the seventh lab of the course; we will do exercises on financial investments exploiting functions and data structures.

**DISCLAIMERS**
- No investing recommendations are given here
- Implemented procedures are exemplified and not guaranteed to be accurate

## Exercise 1: Interests

Create a function called 'calculate_interests' that takes in input:
- 'capital': the amount of money you invest
- 'interest_as_percentage': a number that indicates the percentage of interests
and returns the amount of money earned.

For instance,

    calculate_interests(1000,2)

returns 20.0 (i.e., the 2% of 1000).


In [3]:
def calculate_interests(capital,interest_as_percentage):
    return capital * interest_as_percentage/100

In [8]:
calculate_interests(1000,2)

20.0

## Exercise 2: Compound interests

Interests must be applied every year. Define a function 'invest' that takes in input:
- 'capital': the amount of money you invest
- 'yearly_interest_as_percentage': the interest to be applied **every year**
- 'number_of_year': how many years you plan to invest
and *prints*, year after year, the amount of money earner and the new capital; use 'round(num,2)' to round a number 'num' to 2 decimals.

For instance,

    invest(1000,1,5)

returns

> You start with 1000  
> In the year 1 you have earned 10.0; you now have 1010.0  
> In the year 2 you have earned 10.1; you now have 1020.1  
> In the year 3 you have earned 10.2; you now have 1030.3  
> In the year 4 you have earned 10.3; you now have 1040.6  
> In the year 5 you have earned 10.41; you now have 1051.01

What does it take to get this output?

In [1]:
def invest(capital, yearly_interest_as_percentage, number_of_years):
    print(f"You start with {capital}")
    for i in range(number_of_years):
        interests = calculate_interests(capital,yearly_interest_as_percentage)
        capital = capital + interests
        print(f"In the year {i+1} you have earned {round(interests,2)}; you now have {round(capital,2)}")
    return

In [4]:
invest(1000,1,5)

You start with 1000
In the year 1 you have earned 10.0; you now have 1010.0
In the year 2 you have earned 10.1; you now have 1020.1
In the year 3 you have earned 10.2; you now have 1030.3
In the year 4 you have earned 10.3; you now have 1040.6
In the year 5 you have earned 10.41; you now have 1051.01


## Exercise 3: Calculate the profit

Define a function 'invest2' that works as above, but also calculates the profit at the end of the investment.

For instance,

    invest2(1000,1,5)

returns the following (only the last line is different from Exercise 2)

> You start with 1000  
> In the year 1 you have earned 10.0; you now have 1010.0  
> In the year 2 you have earned 10.1; you now have 1020.1  
> In the year 3 you have earned 10.2; you now have 1030.3  
> In the year 4 you have earned 10.3; you now have 1040.6  
> In the year 5 you have earned 10.41; you now have 1051.01
> In the end, your profit is 51.01

What does it take to get this output?

In [41]:
def invest2(capital, yearly_interest_as_percentage, number_of_years):
    initialInvestment = capital
    
    print(f"You start with {capital}")
    for i in range(number_of_years):
        interests = calculate_interests(capital,yearly_interest_as_percentage)
        capital = capital + interests
        print(f"In the year {i+1} you have earned {round(interests,2)}; you now have {round(capital,2)}")
    
    profit = capital - initialInvestment
    
    print(f"In the end, your profit is {round(profit,2)}")
    return

In [42]:
invest2(1000,1,5)

You start with 1000
In the year 1 you have earned 10.0; you now have 1010.0
In the year 2 you have earned 10.1; you now have 1020.1
In the year 3 you have earned 10.2; you now have 1030.3
In the year 4 you have earned 10.3; you now have 1040.6
In the year 5 you have earned 10.41; you now have 1051.01
In the end, your profit is 51.01


## Exercise 4: Taxes

Profits must be taxed. Define a function 'remove_taxes' that takes in input:
- 'amount': an amount of money
- 'tax_percentage': the percentage of taxes to apply
and returns the amount without taxes.

For instance,

    remove_taxes(1000,26)

returns 740.0 (i.e., 1000-26%).

In [5]:
def remove_taxes(amount, tax_percentage):
    return amount * (1-(tax_percentage/100))

In [58]:
remove_taxes(1000,26)

740.0

## Exercise 5: Include taxes in the investment

Define a function 'invest3' that works as 'invest2', but also removes taxes from the profit. The percentage of taxes must be given in input, with a default value of 26. **Notice**: taxes are applied only if the profit is positive! 

For instance,

    invest3(1000,1,5)

returns the following

> You start with 1000  
> In the year 1 you have earned 10.0; you now have 1010.0  
> In the year 2 you have earned 10.1; you now have 1020.1  
> In the year 3 you have earned 10.2; you now have 1030.3  
> In the year 4 you have earned 10.3; you now have 1040.6  
> In the year 5 you have earned 10.41; you now have 1051.01  
> Your gross profit is 51.01  
> After taxes, your net profit is 37.75, so you end up with a total of 1037.75

In [7]:
def invest3(capital, yearly_interest_as_percentage, number_of_years, tax_percentage=26):
    initialInvestment = capital
    
    print(f"You start with {capital}")
    for i in range(number_of_years):
        interests = calculate_interests(capital,yearly_interest_as_percentage)
        capital = capital + interests
        print(f"In the year {i+1} you have earned {round(interests,2)}; you now have {round(capital,2)}")
    
    profit = capital - initialInvestment

    if profit>0:
        print(f"Your gross profit is {round(profit,2)}")
        profit = remove_taxes(profit,tax_percentage)
    
    print(f"After taxes, your net profit is {round(profit,2)}, so you end up with a total of {round(initialInvestment+profit,2)}")
    return

In [8]:
invest3(1000,-1,5)

You start with 1000
In the year 1 you have earned -10.0; you now have 990.0
In the year 2 you have earned -9.9; you now have 980.1
In the year 3 you have earned -9.8; you now have 970.3
In the year 4 you have earned -9.7; you now have 960.6
In the year 5 you have earned -9.61; you now have 950.99
After taxes, your net profit is -49.01, so you end up with a total of 950.99


## Exercise 6: Include costs in the investment

Usually, investments have costs, that must be considered every year. The percentage of costs must be given in input, with a default value of 2. **Notice**: every year, costs are calculated based on the value of capital+interests in such year.

Define a function 'invest4' that works like 'invest3' but also includes the costs. For instance,

    invest4(1000,1,5)

returns the following

> You start with 1000  
> In the year 1 you have earned 10.0 and paid 5.05; you now have 1004.95  
> In the year 2 you have earned 10.05 and paid 5.07; you now have 1009.92  
> In the year 3 you have earned 10.1 and paid 5.1; you now have 1014.92  
> In the year 4 you have earned 10.15 and paid 5.13; you now have 1019.95  
> In the year 5 you have earned 10.2 and paid 5.15; you now have 1025.0  
> Your gross profit is 25.0  
> After taxes, your net profit is 18.5, so you end up with a total of 1018.5  

In [9]:
def invest4(capital, yearly_interest_as_percentage, number_of_years, tax_percentage=26, yearly_cost_as_percentage=2):
    initialInvestment = capital
    
    print(f"You start with {capital}")
    for i in range(number_of_years):
        interests = calculate_interests(capital,yearly_interest_as_percentage)
        # costs = calculate_interests(capital+interests,yearly_cost_as_percentage)
        costs = (capital+interests) * yearly_cost_as_percentage/100
        capital = capital + interests - costs
        print(f"In the year {i+1} you have earned {round(interests,2)} and paid {round(costs,2)}; you now have {round(capital,2)}")
    
    profit = capital - initialInvestment

    if profit>0:
        print(f"Your gross profit is {round(profit,2)}")
        profit = remove_taxes(profit,tax_percentage)
    
    print(f"After taxes, your net profit is {round(profit,2)}, so you end up with a total of {round(initialInvestment+profit,2)}")
    return

In [10]:
invest4(1000,1,5,yearly_cost_as_percentage=0.5)

You start with 1000
In the year 1 you have earned 10.0 and paid 5.05; you now have 1004.95
In the year 2 you have earned 10.05 and paid 5.07; you now have 1009.92
In the year 3 you have earned 10.1 and paid 5.1; you now have 1014.92
In the year 4 you have earned 10.15 and paid 5.13; you now have 1019.95
In the year 5 you have earned 10.2 and paid 5.15; you now have 1025.0
Your gross profit is 25.0
After taxes, your net profit is 18.5, so you end up with a total of 1018.5


## Exercise 7: Variable interests

Interests change every year, and they are not always positive. Define a function 'invest5' that works like 'invest4', but where:
- the parameter 'yearly_interest_as_percentage' is replaced with 'yearly_interests_as_percentages' as a list of interests
- the parameter 'number_of_years' is not needed anymore (it is implict in the length of 'yearly_interests_as_percentages')

For instance,

    invest5(1000,[1,-2,3,-4,5],yearly_cost_as_percentage=0.5)

returns the following

> You start with 1000
> In the year 1 you have earned 10.0 and paid 5.05; you now have 1004.95  
> In the year 2 you have earned -20.1 and paid 4.92; you now have 979.93  
> In the year 3 you have earned 29.4 and paid 5.05; you now have 1004.28  
> In the year 4 you have earned -40.17 and paid 4.82; you now have 959.29  
> In the year 5 you have earned 47.96 and paid 5.04; you now have 1002.21  
> Your gross profit is 2.21  
> After taxes, your net profit is 1.64, so you end up with a total of 1001.64

In [11]:
def invest5(capital, yearly_interests_as_percentages, tax_percentage=26, yearly_cost_as_percentage=2):
    initialInvestment = capital
    
    print(f"You start with {capital}")
    for year in range(len(yearly_interests_as_percentages)):
        interests = calculate_interests(capital,yearly_interests_as_percentages[year])
        costs = calculate_interests(capital+interests,yearly_cost_as_percentage)
        capital = capital + interests - costs
        print(f"In the year {year+1} you have earned {round(interests,2)} and paid {round(costs,2)}; you now have {round(capital,2)}")
    
    profit = capital - initialInvestment

    if profit>0:
        print(f"Your gross profit is {round(profit,2)}")
        profit = remove_taxes(profit,tax_percentage)
    
    print(f"After taxes, your net profit is {round(profit,2)}, so you end up with a total of {round(initialInvestment+profit,2)}")
    return

In [16]:
# invest5(1000,[-10,-15,0,10,8,15,20],yearly_cost_as_percentage=0.5)
invest5(1000,[10,8,15,20,-10,-15,0],yearly_cost_as_percentage=0.5)
invest5(1000,[10,8,15,20,-10,-15,0],yearly_cost_as_percentage=2)

You start with 1000
In the year 1 you have earned 100.0 and paid 5.5; you now have 1094.5
In the year 2 you have earned 87.56 and paid 5.91; you now have 1176.15
In the year 3 you have earned 176.42 and paid 6.76; you now have 1345.81
In the year 4 you have earned 269.16 and paid 8.07; you now have 1606.9
In the year 5 you have earned -160.69 and paid 7.23; you now have 1438.98
In the year 6 you have earned -215.85 and paid 6.12; you now have 1217.01
In the year 7 you have earned 0.0 and paid 6.09; you now have 1210.93
Your gross profit is 210.93
After taxes, your net profit is 156.09, so you end up with a total of 1156.09
You start with 1000
In the year 1 you have earned 100.0 and paid 22.0; you now have 1078.0
In the year 2 you have earned 86.24 and paid 23.28; you now have 1140.96
In the year 3 you have earned 171.14 and paid 26.24; you now have 1285.86
In the year 4 you have earned 257.17 and paid 30.86; you now have 1512.17
In the year 5 you have earned -151.22 and paid 27.22; you

## Exercise 8: Make it a dict

Instead of just printing data, put everything into a dictionary structured as follows.

    {
        initialInvestment: 1000
        yearlyInvestments: [
            {initialCapital: 1000, year: 1, interest_perc: 1, interests: 10.0, cost: 5.05, newCapital: 1004.95}
            ...    
        ]
        grossProfit: 2.21
        netProfit: 1.64
        finalAmount: 1001.64
    }

In [ ]:
## Solution to-be-published!

## Exercise 9: Variable capital

Instead of having just an initialCapital, give in input a list containg the amount of money you add every year. For instance, with:

    invest6([1000,100,100,100,100],[1,-2,3,-4,5],yearly_cost_as_percentage=0.5)

you start with 1000 the first year and 100 every subsequent year.

In [ ]:
## Solution to-be-published!

## Exercise 10: Portfolio

Let's simulate the case where you have a portfolio of multiple investments, each with its own interest rates and costs.

Define your portfolio as a list of dictionaries, like this:

    [
        {
            capital: [1000,100,100,100,100]
            interests: [1,-2,3,-4,5]
            yearly_costs: 0.05
        }
        {
            ...
        }
    ]

and calculate your expected profits.

In [ ]:
## Solution to-be-published!

## Exercise 11: Millionaire

Assume that the market increases every year by 5% and that, every year, you are able to add X euros to your investment. How much does X have to be so that you reach 1 million in less than 30 years? Find it out without trying manually different values of X.

In [ ]:
## Solution to-be-published!